### ISSUE TITLE
Bug: AtlasQuests Won't Work on 3.4.1 Correctly

### ISSUE THREAD

**Issue by PassCody** [thandrenn/AtlasQuest#16]
Atlas quests do not show the quests I can accept for the instances.
So there are no menu items and no texts from who and where you get the quest and the rewards.

**Comment by thandrenn** [comment]
The last patch changed a function I've used for years in a really weird way.  I've uploaded a beta with a fix that I hope works.  It only applies to Northrend maps currently but if successful I will correct the other maps.

https://www.curseforge.com/wow/addons/atlas-quest-fan-update/files/4375577

**Comment by thandrenn** [comment]
Issue corrected by Zilom in new release.
