### ISSUE TITLE
Remaining retail (DF) errors

### ISSUE THREAD

**Issue by reaper666735** [thandrenn/AtlasQuest#18]
Hello,

i know you mentioned DF changed allot and that you might not be able to fix the addon fully for retail, i simply wanted to 'regroup' the remaining lua's i have been getting and hopefully in time (or with Zilom's help ;) ) they might be ancient history ^^

84x AtlasQuest/AtlasQuest_InsideFrame.xml:448 Couldn't find inherited node: OptionsCheckButtonTemplate

84x AtlasQuest/AtlasQuest.xml:74 Unrecognized XML: Backdrop

84x AtlasQuest/AtlasQuest.xml:74 Unrecognized XML attribute: name

84x AtlasQuest/AtlasQuest.xml:74 Unrecognized XML attribute: bgFile

84x AtlasQuest/AtlasQuest.xml:74 Unrecognized XML attribute: edgeFile

84x AtlasQuest/AtlasQuest.xml:74 Unrecognized XML attribute: tile

84x AtlasQuest/AtlasQuest.xml:75 Unrecognized XML: EdgeSize

83x AtlasQuest/AtlasQuest.xml:76 Unrecognized XML: AbsValue

83x AtlasQuest/AtlasQuest.xml:76 Unrecognized XML attribute: val

82x AtlasQuest/AtlasQuest.xml:78 Unrecognized XML: Color

should any more arise i will add them here :)

**Comment by thandrenn** [comment]
Zilom just fixed up most, if not all of the XML errors.  There will be a Dragonflight release soon.  It won't have the new Dragonflight quests since Atlas hasn't added the maps for them, but it will fix a lot of AtlasQuest's own issues.
