### ISSUE TITLE
Add releases for WoWUp compatibility

### ISSUE THREAD

**Issue by Magikh42** [thandrenn/AtlasQuest#20]
Hello

Would it be possible to add releases with the addon zip in order to permit WoWUp compatibility ?
See https://github.com/WowUp/WowUp/issues/1245#issuecomment-1128360257 for more explanations

**Comment by Magikh42** [comment]
(bump)

**Comment by nanderson11** [comment]
This looks like the format that the Big Wigs Packager uses, which is what I started to implement in #26. Hopefully I should be able to finish that up in the next day or two.

**Comment by Magikh42** [comment]
I think the GitHub action should be modified to generate [releases](https://github.com/thandrenn/AtlasQuest/releases) stead of a [tags](https://github.com/thandrenn/AtlasQuest/tags)

**Comment by nanderson11** [comment]
The github action does generate releases, it's triggered by tags. I just hadn't merged and run the action yet. But I've done that for the 5.2.2 release, so you should be all set. Let me know if it doesn't work for some reason.
