### ISSUE TITLE
wow sod addon is not working with atlas

### ISSUE THREAD

**Issue by Burakiyani** [thandrenn/AtlasQuest#32]
Hi when I start the game with this addon , atlas is not working. there is image showing at near of minimap but when I click on it does not open. But when I disable atlasloot fan update it opens properly. Any solution for this ?

**Comment by nanderson11** [comment]
Hi, can you tell me what what version of Atlas you have installed, as well as what version of the Atlas map packs you have?

And then if you can get me an error message that would be great. You can do that by running `/console scriptErrors 1` in chat and then `/reload ui`. And then you should hopefully get an error message either immediately or when you click on the Atlas button. Copy and paste that here, and then you can do `/console scriptErrors 0` and `/reload ui` to turn errors off again.

**Comment by Burakiyani** [comment]
Message: Interface/AddOns/Atlas/Core/Atlas.lua:203: attempt to index field 'db' (a nil value) ))
Time: Sat Aug 10 22:27:19 2024
Count: 1
Stack: Interface/AddOns/Atlas/Core/Atlas.lua:203: attempt to index field 'db' (a nil value)
[string "@Interface/AddOns/Atlas/Core/Atlas.lua"]:203: in function <Interface/AddOns/Atlas/Core/Atlas.lua:199>
[string "@Interface/AddOns/Atlas/Core/Atlas.lua"]:2033: in function <Interface/AddOns/Atlas/Core/Atlas.lua:2031>
[string "=[C]"]: ?
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...face/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...face/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: moduleKey = "BurningCrusade"
module = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 baseName = "Atlas_BurningCrusade"
 moduleName = "BurningCrusade"
 GetName = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "Atlas_BurningCrusade"
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 IsEnabled = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 DisableModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
(*temporary) = nil
(*temporary) = "BurningCrusade"
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 baseName = "Atlas_BurningCrusade"
 moduleName = "BurningCrusade"
 GetName = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "AMessage: ...ce/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:833: attempt to get length of field 'StaticPopup_DisplayedFrames' (a nil value)
Time: Sat Aug 10 22:27:25 2024
Count: 6
Stack: ...ce/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:833: attempt to get length of field 'StaticPopup_DisplayedFrames' (a nil value)
[string "@Interface/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua"]:833: in function `Spawn'
[string "@Interface/AddOns/Atlas/Core/Atlas.lua"]:1946: in function `isModuleOrPluginLoaded'
[string "@Interface/AddOns/Atlas/Core/Atlas.lua"]:670: in function `Atlas_Toggle'
[string "@Interface/AddOns/Atlas/Core/Atlas.lua"]:1986: in function `OnClick'
[string "@Interface/AddOns/SpecBisTooltip/libs/D4Lib/LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:179: in function <.../D4Lib/LibDBIcon-1.0/LibDBIcon-1.0/LibDBIcon-1.0.lua:177>

Locals: self = <table> {
 active_dialogs = <table> {
 }
 active_buttons = <table> {
 }
 Register = <function> defined @Interface/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:713
 delegate_queue = <table> {
 }
 active_editboxes = <table> {
 }
 Dismiss = <function> defined @Interface/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:876
 checkbox_heap = <table> {
 }
 dialog_heap = <table> {
 }
 queued_delegates = <table> {
 }
 ActiveDialog = <function> defined @Interface/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:858
 hooked_set_up_position = true
 Spawn = <function> defined @Interface/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:749
 delegates = <table> {
 }
 button_heap = <table> {
 }
 hooked_escape_pressed = true
 active_checkboxes = <table> {
 }
 active_icons = <table> {
 }
 editbox_heap = <table> {
 }
 icon_heap = <table> {
 }
 hooked_onhide = true
}
reference = "NeedModuleOrPlugin"
data = nil
delegate = <table> {
 hide_on_escape = true
 buttons = <table> {
 }
 text = "Error:
Atlas can not detect any of map module 
or plugin installed and enabled.
Note that Atlas itself is a map browser, 
you will have to at least install one 
map module or plugin to browse the maps."
 show_while_dead = false
 width = 400
}
cancel_list = nil
dialog = LibDialog-1.0_Dialog1 {
 BottomLeftCorner = Texture {
 }
 close_button = Button {
 }
 backdropInfo = <table> {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 buttons = <table> {
 }
 TopEdge = Texture {
 }
 text = FontString {
 }
 0 = <userdata>
 BottomEdge = Texture {
 }
 delegate = <table> {
 }
 BottomRightCorner = Texture {
 }
 is_new = true
 LeftEdge = Texture {
 }
 Center = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = LibDialog-1.0_Dialog1 {
 BottomLeftCorner = Texture {
 }
 close_button = Button {
 }
 backdropInfo = <table> {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 buttons = <table> {
 }
 TopEdge = Texture {
 }
 text = FontString {
 }
 0 = <userdata>
 BottomEdge = Texture {
 }
 delegate = <table> {
 }
 BottomRightCorner = Texture {
 }
 is_new = true
 LeftEdge = Texture {
 }
 Center = Texture {
 }
}
(*temporary) = 0
(*temporary) = nil
(*temporary) = 2
(*temporary) = 1
(*temporary) = 2
(*temporary) = LibDialog-1.0_Button12 {
 0 = <userdata>
}
(*temporary) = 95.604942
(*temporary) = <function> defined =[C]:-1
(*temporary) = LibDialog-1.0_Button12 {
 0 = <userdata>
}
(*temporary) = <userdata>
(*temporary) = "attempt to get length of field 'StaticPopup_DisplayedFrames' (a nil value)"
_FindDelegate = <function> defined @Interface/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:724
active_dialogs = <table> {
}
delegates = <table> {
 NeedModuleOrPlugin = <table> {
 }
}
error = <function> defined =[C]:-1
_BuildDialog = <function> defined @Interface/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:553
_Dialog_OnShow = <function> defined @Interface/AddOns/Atlas/Libs/LibDialog-1.0/LibDialog-1.0.lua:229 )))

**Comment by Burakiyani** [comment]
version of atlas-v1.52.08  7 / atlasloot classic maps v1.0.0

**Comment by nanderson11** [comment]
I think you might just have the wrong map pack. Atlasloot Classic Maps is for Atlasloot. [Atlas Classic Wow](https://www.curseforge.com/wow/addons/atlas-classicwow) is the map pack for Atlas.

**Comment by Burakiyani** [comment]
Your thinkins are wrong because now I deleted that addon and I download the addon that you have mentioned atlas_classic wow  v1.14.13 still my atlas is not working as long as atlas quest addon is active.

**Comment by Burakiyani** [comment]
ah it is fixed now but solution still not that , I disabled the burning crusade atlas loot , it is fixed!

**Comment by nanderson11** [comment]
Glad you figured it out
