### ISSUE TITLE
AtlasQuest not working with new version of Atlas

### ISSUE THREAD

**Issue by woopydalan** [thandrenn/AtlasQuest#9]
Just wanted to loop you in on this. Not sure where the issue lies.
https://www.curseforge.com/wow/addons/atlas-classicwow/issues/34

**Comment by thandrenn** [comment]
Looks like the map file names were renamed for Classic, so I'll have to update AtlasQuest Classic to match.  This an AtlasQuest issue.   I'll put out an update shortly to correct it

**Comment by thandrenn** [comment]
Okay, I just uploaded 4.11.60 for Classic which should correct the issue.  This was a quick fix as I'm racing the clock before I have to leave to go to work, lol.  Let me know if there's any problems.
